### ISSUE TITLE
[Bug]群组续火失效

### ISSUE THREAD

**Issue by linxDynW** [LuckyPray/XAutoDaily#102]
在QQ版本9.0.65上的群组续火功能没有作用，且显示响应成功执行，但实际上没有消息发出，手动签到也没有效果。

续火自动执行时qq位于前台且弹出执行成功的toast，后续手动签到只显示开始执行签到的提示，但是没有响应，也没有消息发出

模块版本3.0.26-fix，qq版本9.0.65，安卓14，使用lsposed 1.9.2

**Comment by ltxhhz** [comment]
+1
我的是好友续火失效，群组的打不开了，会闪退
模块 3.0.26-fix, qq9.0.75, 安卓14, 配置53, ONPatch 0.0.7
<details>
<summary>日志</summary>

```
2024-07-31T00:19:25.214 20121 XALog: Module path = /data/app/~~IOvdM-YTl3iHwoBkeJZjzg==/me.teble.xposed.autodaily-nrWEWwmBKUVGObOEl3zjrg==/base.apk
2024-07-31T00:19:25.215 20121 XALog: Resources injection result: 资源注入成功
2024-07-31T00:19:25.216 20121 XALog: groupClass: class com.tencent.mobileqq.setting.processor.c
2024-07-31T00:19:26.579 20121 XALog: 开始替换
2024-07-31T00:19:26.580 20121 XALog: 替换完成
2024-07-31T00:19:26.611 20121 XALog: 
java.lang.NoSuchMethodException: android.app.ActivityThread.getLaunchingActivity [interface android.os.IBinder]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at Gz.handleMessage(SourceFile:4)
	at io.github.qauxv.lifecycle.Parasitics$ProxyHandlerCallback.handleMessage(Parasitics.java:384)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8711)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

2024-07-31T00:19:26.627 20121 XALog: Module path = /data/app/~~IOvdM-YTl3iHwoBkeJZjzg==/me.teble.xposed.autodaily-nrWEWwmBKUVGObOEl3zjrg==/base.apk
2024-07-31T00:19:26.628 20121 XALog: Resources injection result: 资源注入成功
2024-07-31T00:19:26.659 20121 XALog: Module path = /data/app/~~IOvdM-YTl3iHwoBkeJZjzg==/me.teble.xposed.autodaily-nrWEWwmBKUVGObOEl3zjrg==/base.apk
2024-07-31T00:19:26.659 20121 XALog: Resources injection result: 资源注入成功
2024-07-31T00:19:31.999 20121 XALog: regex find result -> ["$minute","$hour"]
2024-07-31T00:19:32 20121 XALog: name -> minute
2024-07-31T00:19:32.001 20121 XALog: value -> 0
2024-07-31T00:19:32.001 20121 XALog: name -> hour
2024-07-31T00:19:32.002 20121 XALog: value -> 0
2024-07-31T00:19:32.002 20121 XALog: evalString -> 0 $minute $hour * * *
2024-07-31T00:19:32.002 20121 XALog: formatArgs -> ["minute","hour"]
2024-07-31T00:19:32.003 20121 XALog: formatValues -> ["0","0"]
2024-07-31T00:19:32.003 20121 XALog: format -> [0 0 0 * * *]
2024-07-31T00:19:32.088 20121 XALog: 当前filter -> GroupTaskCheckExecuteFilter
2024-07-31T00:19:32.089 20121 XALog: task -> 好友续火花 将被执行
2024-07-31T00:19:32.089 20121 XALog: 当前filter -> GroupTaskPreFilter
2024-07-31T00:19:32.090 20121 XALog: groupTask -> 好友相关 任务类型为: func
2024-07-31T00:19:32.090 20121 XALog: 当前filter -> GroupTaskRelayBuilderFilter
2024-07-31T00:19:32.090 20121 XALog: 当前filter -> GroupTaskExecuteBasicFilter
2024-07-31T00:19:32.091 20121 XALog: 开始执行任务：好友续火花
2024-07-31T00:19:32.091 20121 XALog: 开始获取用户自定义变量：friends, 用户自定义值为：(uin), 默认值：
2024-07-31T00:19:32.091 20121 XALog: 开始获取用户自定义变量：message, 用户自定义值为：古德猫宁, 默认值：
2024-07-31T00:19:32.091 20121 XALog: 开始获取用户自定义变量：hour, 用户自定义值为：0, 默认值：7
2024-07-31T00:19:32.092 20121 XALog: 开始获取用户自定义变量：minute, 用户自定义值为：0, 默认值：0
2024-07-31T00:19:32.094 20121 XALog: regex find result -> []
2024-07-31T00:19:32.094 20121 XALog: evalString -> 1
2024-07-31T00:19:32.094 20121 XALog: formatArgs -> []
2024-07-31T00:19:32.095 20121 XALog: formatValues -> []
2024-07-31T00:19:32.095 20121 XALog: format -> [1]
2024-07-31T00:19:32.095 20121 XALog: 重复请求次数 -> 1
2024-07-31T00:19:32.096 20121 XALog: regex find result -> ["${friends}$","${message}$"]
2024-07-31T00:19:32.096 20121 XALog: name -> friends
2024-07-31T00:19:32.096 20121 XALog: value -> [(uin)]
2024-07-31T00:19:32.096 20121 XALog: name -> message
2024-07-31T00:19:32.097 20121 XALog: value -> 古德猫宁
2024-07-31T00:19:32.097 20121 XALog: evalString -> xa://SendMessageManager/sendMessage/friend?uin=${friends}$&msg=${message}$
2024-07-31T00:19:32.097 20121 XALog: formatArgs -> ["friends","message"]
2024-07-31T00:19:32.097 20121 XALog: formatValues -> [["(uin)"],"古德猫宁"]
2024-07-31T00:19:32.098 20121 XALog: format -> [xa://SendMessageManager/sendMessage/friend?uin=(uin)&msg=古德猫宁]
2024-07-31T00:19:32.098 20121 XALog: urls -> ["xa://SendMessageManager/sendMessage/friend?uin=(uin)&msg=古德猫宁"]
2024-07-31T00:19:42.099 20121 XALog: paramMap -> {uin=(uin), msg=古德猫宁}
2024-07-31T00:19:42.100 20121 XALog: --------xa://SendMessageManager/sendMessage/friend?uin=(uin)&msg=古德猫宁-------
2024-07-31T00:19:42.101 20121 XALog: handleCallback -> 
   success: true
   msg: 执行成功
2024-07-31T00:19:42.103 20121 XALog: regex find result -> ["$minute","$hour"]
2024-07-31T00:19:42.103 20121 XALog: name -> minute
2024-07-31T00:19:42.104 20121 XALog: value -> 0
2024-07-31T00:19:42.104 20121 XALog: name -> hour
2024-07-31T00:19:42.105 20121 XALog: value -> 0
2024-07-31T00:19:42.106 20121 XALog: evalString -> 0 $minute $hour * * *
2024-07-31T00:19:42.106 20121 XALog: formatArgs -> ["minute","hour"]
2024-07-31T00:19:42.107 20121 XALog: formatValues -> ["0","0"]
2024-07-31T00:19:42.107 20121 XALog: format -> [0 0 0 * * *]
2024-07-31T00:19:49.568 20121 XALog: Module path = /data/app/~~IOvdM-YTl3iHwoBkeJZjzg==/me.teble.xposed.autodaily-nrWEWwmBKUVGObOEl3zjrg==/base.apk
2024-07-31T00:19:49.569 20121 XALog: Resources injection result: 资源注入成功
2024-07-31T00:19:49.569 20121 XALog: groupClass: class com.tencent.mobileqq.setting.processor.c
2024-07-31T00:19:50.860 20121 XALog: 开始替换
2024-07-31T00:19:50.862 20121 XALog: 替换完成
2024-07-31T00:19:50.901 20121 XALog: 
java.lang.NoSuchMethodException: android.app.ActivityThread.getLaunchingActivity [interface android.os.IBinder]
	at java.lang.Class.getMethod(Class.java:2937)
	at java.lang.Class.getMethod(Class.java:2449)
	at Gz.handleMessage(SourceFile:4)
	at io.github.qauxv.lifecycle.Parasitics$ProxyHandlerCallback.handleMessage(Parasitics.java:384)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8711)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

2024-07-31T00:19:50.915 20121 XALog: Module path = /data/app/~~IOvdM-YTl3iHwoBkeJZjzg==/me.teble.xposed.autodaily-nrWEWwmBKUVGObOEl3zjrg==/base.apk
2024-07-31T00:19:50.916 20121 XALog: Resources injection result: 资源注入成功
2024-07-31T00:19:50.946 20121 XALog: Module path = /data/app/~~IOvdM-YTl3iHwoBkeJZjzg==/me.teble.xposed.autodaily-nrWEWwmBKUVGObOEl3zjrg==/base.apk
2024-07-31T00:19:50.947 20121 XALog: Resources injection result: 资源注入成功
2024-07-31T00:19:59.615 20121 XALog: 定时执行
2024-07-31T00:20:19.672 20121 XALog: Module path = /data/app/~~IOvdM-YTl3iHwoBkeJZjzg==/me.teble.xposed.autodaily-nrWEWwmBKUVGObOEl3zjrg==/base.apk
2024-07-31T00:20:19.673 20121 XALog: Resources injection result: 资源注入成功

```

</details>

**Comment by teble** [comment]
qq 75+ 置空了旧版发送消息函数中的代码，但是并没有删除方法所以日志并不会表现异常。目前每天只能抽一点时间来理逻辑重写这部分，我自己续火都没得用还得花点时间才能搞定。获取群列表那边处理75+也炸了，目前已修复但是要等发消息后才能发版

**Comment by teble** [comment]
> 在QQ版本9.0.65上的群组续火功能没有作用，且显示响应成功执行，但实际上没有消息发出，手动签到也没有效果。
> 
> 续火自动执行时qq位于前台且弹出执行成功的toast，后续手动签到只显示开始执行签到的提示，但是没有响应，也没有消息发出
> 
> 模块版本3.0.26-fix，qq版本9.0.65，安卓14，使用lsposed 1.9.2

旧版发消息API是没有回调的，到底有没有执行，模块是获取不到的，而且旧API发送的消息是有概率在UI层面被吞（即：发出去了，但是并不会显示，需要通过其它客户端才知道到底发没发），新的发消息API能拿到消息发送的回调，可以比较好的解决之前的问题

**Comment by linxDynW** [comment]
> > 在QQ版本9.0.65上的群组续火功能没有作用，且显示响应成功执行，但实际上没有消息发出，手动签到也没有效果。
> > 
> > 续火自动执行时qq位于前台且弹出执行成功的toast，后续手动签到只显示开始执行签到的提示，但是没有响应，也没有消息发出
> > 
> > 模块版本3.0.26-fix，qq版本9.0.65，安卓14，使用lsposed 1.9.2
> 
> 旧版发消息API是没有回调的，到底有没有执行，模块是获取不到的，而且旧API发送的消息是有概率在UI层面被吞（即：发出去了，但是并不会显示，需要通过其它客户端才知道到底发没发），新的发消息API能拿到消息发送的回调，可以比较好的解决之前的问题

确实是没有发出去，在同一个群别的号没有看到，而且确实有一个断火了

**Comment by AilaSama** [comment]
> +1 我的是好友续火失效，群组的打不开了，会闪退 模块 3.0.26-fix, qq9.0.75, 安卓14, 配置53, ONPatch 0.0.7
> 
> 日志

一样，但我是安卓13，也会遇到闪退问题

**Comment by block13566** [comment]
同样，群组续火功能会闪退

**Comment by teble** [comment]
3.0.27已修复
